version: "3"

volumes:
    node_data: {}

networks:
    node-net:
        external: true

services:
    server:
        image: node:12.22.3-alpine

        container_name: nodejs
        environment:
            - WSDL_CORREIOS=https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService
            - METHOD=text/xml;charset=UTF-8
            - DB_HOST=db
            - DB_USER=postgres
            - DB_PASS=123456
            - DB_DATABASE=coordenadas
            - NODE_ENV=development
            - SCHEDULE_TIME=*/1 * * * *
        networks:
            - node-net
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure
        volumes:
            - "./:/home/app/"
        depends_on:
            - db
        links:
            - db
        command: sh -c "cd /home/app && npm install --save && npm run migrate && npm run seed && npm run start"
    db:
        image: postgres:alpine
        container_name: postgres
        networks:
            - node-net
        restart: on-failure
        deploy:
            restart_policy:
                condition: on-failure
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=coordenadas
        ports:
            - 5432:5432
